<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<title>Apify </title>
<link href="https://a248.e.akamai.net/assets.github.com/391d5709865ba8f75ae0caafdde5f784c8b15fc9/stylesheets/bundle_github.css" media="screen" rel="stylesheet" type="text/css" />
</head>

<body>

<div id="main">

<div class="site">

    <div id="readme" class="announce">
        <div class="wikistyle">
        <?php echo $view->layout()->content; ?>
        </div>
    </div>

    <br style="clear: both;">

</div>

</div>

<?php echo isset($view->layout()->scripts) ? ltrim($view->layout()->scripts, "\r\n") : '' ?>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function()    {
	// do something
});
</script>
</body>

</html>
